options:
  preview: "{{ site.frontendUrl }}"

tabs:
  dashboard:
    label: Dashboard
    icon: draft
    columns:
      - width: 1/2
        sections:
          notes:
            type: pages
            label:
              en: Notes
              de: Notizen
              fr: Notes
              nl: Notities
            layout: cards
            parent: kirby.page("notes")
            create: note
            image:
              query: page.cover.toFile
              cover: true
              back: white

      - width: 1/2
        sections:
          pages:
            type: pages
            create: default
            label:
              en: Pages
              de: Seiten
              fr: Pages
              nl: Pagina's
            image:
              query: page.cover.toFile
              cover: true
              back: white

  settings:
    label:
      en: Settings
      de: Einstellungen
      fr: Paramètres
      nl: Instellingen
    icon: settings
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              footer:
                label:
                  en: Footer
                  de: Fußzeile
                  fr: Pied de page
                  nl: Voettekst
                type: pages
                image:
                  query: page.cover.toFile
                  cover: true
                  back: white

      - width: 1/2
        sections:
          meta:
            type: fields
            fields:
              cover:
                extends: fields/cover
                query: site.files.template("image")
                translate: false
              description: fields/description
